version: "3.8"
services:
  online_shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-shop
    networks:
      - project-network
    ports:
      - 3000:80
    restart: always
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:80/"]
     interval: 60s
     timeout: 10s
     retries: 5


networks:
  project-network:
    driver: bridge

